apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: meta-agents-v2
  labels:
    app: meta-agents-v2
spec:
  template:
    metadata:
      labels:
        app: meta-agents-v2
    agents:
      - WorkflowBuilder
    prompt: |
      stock_data_retriever – Retrieves current stock prices for Apple (AAPL) and Microsoft (MSFT).
      financial_historical_data_retriever – Retrieves historical stock data for the past week for both companies.
      stock_performance_analyzer – Analyzes which stock has performed better over the past week based on historical data.
      prompt:  I want to fetch the current stock prices for Apple and Microsoft, and then analyze which one has performed better over the past week. 
    steps:
      - name: step1
        agent: WorkflowBuilder