apiVersion: maestro/v1alpha1
kind: Agent
metadata:
  name: Temperature Agent
  labels:
    app: label value with space
spec:
  model: "llama3.1:latest"
  framework: beeai
  mode: remote
  description: Get the current weather
  tools:
    - code_interpreter
    - weather
  instructions: An input is given of a location.  Use the OpenMeteo tool to get today's current forecast for the location. Return results in the format - location, temperature in Fahrenheit, and date.
---
apiVersion: maestro/v1alpha1
kind: Agent
metadata:
  name: hot-or-not Agent
  labels:
    app: mas-example
spec:
  model: "llama3.1:latest"
  framework: beeai
  mode: remote
  description: Is the current temperature hotter than usual?
  tools:
    - code_interpreter
    - weather
  instructions: |
    Use the OpenMeteo weather tool to find the historical temperature of the given location.  Return whether the current temperature is hotter or colder.

    Example Process:
    Input: New York, 50 degrees F

    Compare input against historical temperature (lets say 55) in input location.

    Output: The current temperature is colder than the historical temperature.

# ---
# apiVersion: maestro/v1alpha1
# kind: Agent
# metadata:
#   name: score
#   labels: 
#     app: test-example
#     custom_agent: scoring_agent
# spec:
#   model: deepseek-r1:latest
#   framework: custom
#   mode: remote
#   description: gets score, relevance/hallucination using defined model
#   instructions: evaluates the response using Opik


