apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: quri-ai
  labels:
    project: maestro-demo
spec:
  template:
    metadata:
      name: quri-ai
      labels:
        project: maestro-demo
    agents:
      - pubchem agent
      - open fermion
      - mock quri
      - news patents papers
      - generate summary
    prompt: Water
    steps:
      - name: Step1
        agent: pubchem agent 
      - name: Step2
        agent: open fermion
      - name: Step3
        agent: mock quri
      - name: Step4
        agent: news patents papers
      - name: Step5
        agent: generate summary
