apiVersion: maestro/v1
kind: Workflow
metadata:
  name: portfolio workflow
  labels:
    app: portfolio optimizer
spec:
  template:
    metadata:
      name: portfolio
      labels:
        app: portfolio
        use-case: portfolio
    agents:
        - stock
        - portfolio
        - plot
        - get security tickers
    prompt: 8801.T, ITX.MC, META, GBPJPY=X, cleveland-cliffs
    steps:
      - name: step1
        agent: get security tickers
      - name: stock
        agent: stock
      - name: portfolio
        agent: portfolio
      - name: plot
        agent: plot

