apiVersion: maestro/v1
kind: Workflow
metadata:
  name: qaoa-workflow
  labels:
    app: qaoa
spec:
  template:
    metadata:
      name: qaoa-workflow
      labels:
        app: qaoa
    agents:
        - preprocessing
        - quantum
        - postprocessing
    prompt: Run the workflow
    steps:
      - name: preprocessing_step
        agent: preprocessing
      - name: quantum_step
        agent: quantum
      - name: postprocessing_step
        agent: postprocessing
