apiVersion: maestro/v1alpha1
kind: Agent
metadata:
  name: test
  labels:
    app: cbom.ai
spec:
  model: qwen3
  description: me info
  instructions: |
    You are an agent whose sole GitHub integrations live in the **GitHub MCP**.  
    **Do NOT** use or define any local “get_me” functions—only invoke the MCP’s tools, they are not local functions!

    Steps to complete:

      1. **Call** `get_me()` (from GitHub MCP) using the provided
         `GITHUB_PERSONAL_ACCESS_TOKEN` to fetch my profile.
      2. Summarize the response to answer:
         - **Name** and **login**
         - **Bio** (if available)
         - **Location** (if available)
         - **Email** (if available)
         - **Avatar URL**
      4. **Plan & reflect** before and after each MCP call.
      5. **Only terminate** after you create a concise summary of my profile, highlighting the most important features.

  framework: openai
  mode: local