apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: openai_test_mcp_ollama
  labels:
    app: testapp_mcp_ollama
spec:
  template:
    metadata:
      labels:
        app: testapp_mcp_ollama
    agents:
      - test
    prompt: |
      I want to learn about the authenticated GitHub user (myself).
      1. Use the get_me() tool in Github MCP to call to get my user profile, and then output a summary of my profile.
      **Rules:**  
      - Only terminate your turn once your summary fully answers “Who am I?” on GitHub.  
    steps:
    - name: step1
      agent: test