apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: meta_agent_workflow
  labels:
    project: maestro-demo
spec:
  template:
    metadata:
      name: meta_agent_workflow
      labels:
        project: maestro-demo
    agents:
      - NLP Agent Planner V2
      - Format Workflow Agent V2
      - Workflow V2
      - markdown formatter
      - tagger agent
    prompt: I want 4 agents in order to ultimately decide what activities I should do in a given location. First agent get the current temperature given a location, the second to compare that temperature with historical temperatures, then another agent to provide a list of activities if it's cold or conversely another agent to proivde a list of activities if it is hot.
    steps:
      - name: English Instructions to Prompt
        agent: NLP Agent Planner V2
      - name: Specify Agents for Workflow Generation
        agent: Format Workflow Agent V2
      - name: Creating Workflow YAML file
        agent: Workflow V2
      - name: Readable output
        agent: markdown formatter
      - name: add tags
        agent: tagger agent