activity_finder_task:
  description: >
    Find a list of 5 activities to do in the location mentioned in the prompt below.
    Make sure the information is current as of 2025.
    Do not include any additional text in the final answer.
    {prompt}

  expected_output: >
    A list of 5 activities to do in the cold or wet weather in the location mentioned in the {prompt} with
    the name of the activity, a brief description, and the address of the
    location.
  agent: activity_planner_agent