apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: meta-agents-v2
  labels:
    app: meta-agents-v2
spec:
  template:
    metadata:
      labels:
        app: meta-agents-v2
    agents:
      - TaskInterpreter
      - AgentYAMLBuilder
    prompt: I want to fetch the current stock prices for Apple and Microsoft, and then analyze which one has performed better over the past week.
    steps:
    - name: step1
      agent: TaskInterpreter
    - name: step2
      agent: AgentYAMLBuilder