name: Test Demos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  demo-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        curl https://raw.githubusercontent.com/AI4quantum/maestro/refs/heads/main/schemas/agent_schema.json > agent_schema.json
        curl https://raw.githubusercontent.com/AI4quantum/maestro/refs/heads/main/schemas/workflow_schema.json > workflow_schema.json
        pip install --upgrade pip
        pip install git+https://github.com/AI4quantum/maestro.git@v0.3.0
        pip install "beeai-framework[duckduckgo]"
    - name: Check maestro CLI installation
      run: |
        source .venv/bin/activate
        which maestro
        maestro --version
    - name: Run demo tests
      run: |
        ./tools/run-demos.sh
