name: Test Demos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  demo-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install git+https://github.com/AI4quantum/maestro.git@main
        pip install "beeai-framework[duckduckgo]"
    - name: Check maestro CLI installation & run demo tests
      run: |
        source .venv/bin/activate
        which maestro
        maestro --version
        ./tools/run-demos.sh
